[package]
name = "async-await"
version = "0.1.0"
edition = "2024"

[dependencies]
error-chain = "0.12.4"
reqwest = {version = "0.13.1", features = ["blocking", "json"]}
tokio = {version = "1.49.0", features = ["full", "macros"]}

